 ### Multiple Linear Regression used to predict the health of individuals on a scale of 0-100

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Rating: Sleep= 1 to 12 hours, Exercise= 0 to 180 minutes, Diet= scale of 0 to 100 , Genetics= good/average/poor. Output= health on a scale of 0-100.

In [7]:
from numpy.random import rand
s= np.random.uniform(low=1, high=13, size=(33)).astype(float)
s

array([ 9.01751445,  8.24117179,  8.89874437,  7.03945084,  2.70923849,
       10.64669502,  6.5948128 ,  9.05032728,  6.97836466,  3.13533126,
        8.89380478,  8.94778718, 11.49557031,  4.40500469, 12.27238884,
        9.51144138,  9.42161099,  6.50164778,  8.77723374,  4.95605836,
       10.31717981, 11.35127059,  7.31103896,  4.82739354,  8.0689794 ,
        8.07618097,  3.84400747, 12.28297858, 11.24536189,  3.3367289 ,
        8.60235388,  7.92670888,  1.33568135])

In [9]:
ex= np.random.uniform(low=0, high=181, size=(33)).astype(int)
ex

array([ 72, 114,  78,  90,  76,  66,  95,  83, 156, 133,  78, 176,  87,
       128, 179, 113, 114,  15, 122, 161,  35,  70, 144, 133,  27, 126,
       129, 136, 137,  61,  88,  39, 108])

In [11]:
d= np.random.uniform(low=0, high=101, size=(33)).astype(float)
d

array([ 61.42402005,  85.12581225,  73.04413967,  39.10886975,
        72.65817602,  65.96698862,  55.1903074 ,  68.76417963,
        83.48024229,  98.79451758,  68.43089379,  14.3671272 ,
       100.42762265,  14.34448731,  35.67973869,  99.83841631,
        25.30084774,  96.94999827,  53.27558889,  15.15782314,
       100.72749782,  41.15021639,  23.49353665,  78.49659148,
        84.45359422,  48.29231688,  50.08919029,  87.04858555,
        66.39675675,  15.6326242 ,  88.725557  ,  21.49084912,
        34.13408711])

In [15]:
from random import choice
gene=[]
for i in range(1,34):
    gene.append(choice(['good','average','poor'])) 
gene

['poor',
 'good',
 'poor',
 'average',
 'good',
 'poor',
 'poor',
 'good',
 'poor',
 'poor',
 'poor',
 'average',
 'good',
 'poor',
 'poor',
 'good',
 'average',
 'poor',
 'good',
 'average',
 'good',
 'good',
 'good',
 'good',
 'poor',
 'good',
 'average',
 'good',
 'good',
 'good',
 'good',
 'poor',
 'good']

In [16]:
len(gene)

33

In [26]:
list1=[]
for i in range(0,33):
    list1.append((s[i],ex[i],d[i],gene[i]))
list1

[(9.017514446686404, 72, 61.424020046481466, 'poor'),
 (8.241171789738818, 114, 85.12581225307461, 'good'),
 (8.898744366814949, 78, 73.04413967158837, 'poor'),
 (7.039450841845602, 90, 39.10886974518282, 'average'),
 (2.709238494933037, 76, 72.65817601850354, 'good'),
 (10.646695022583927, 66, 65.96698862454234, 'poor'),
 (6.594812803950399, 95, 55.19030740308224, 'poor'),
 (9.050327275174146, 83, 68.76417963034481, 'good'),
 (6.978364658693472, 156, 83.48024228929242, 'poor'),
 (3.135331258365633, 133, 98.79451757919034, 'poor'),
 (8.8938047787449, 78, 68.43089378748391, 'poor'),
 (8.947787177821851, 176, 14.367127196131682, 'average'),
 (11.49557030809757, 87, 100.42762265260484, 'good'),
 (4.40500469185009, 128, 14.344487305738099, 'poor'),
 (12.272388839254457, 179, 35.67973869105069, 'poor'),
 (9.511441381805257, 113, 99.83841630835056, 'good'),
 (9.42161099435678, 114, 25.300847737454188, 'average'),
 (6.501647784097692, 15, 96.94999826726865, 'poor'),
 (8.777233742131408, 122, 

In [29]:
df1= pd.DataFrame(list1, columns=['hours_slept','minutes_exercised','diet_rating','genetic_factors'])
df1

hours_slept  minutes_exercised  diet_rating genetic_factors
0      9.017514                 72    61.424020            poor
1      8.241172                114    85.125812            good
2      8.898744                 78    73.044140            poor
3      7.039451                 90    39.108870         average
4      2.709238                 76    72.658176            good
5     10.646695                 66    65.966989            poor
6      6.594813                 95    55.190307            poor
7      9.050327                 83    68.764180            good
8      6.978365                156    83.480242            poor
9      3.135331                133    98.794518            poor
10     8.893805                 78    68.430894            poor
11     8.947787                176    14.367127         average
12    11.495570                 87   100.427623            good
13     4.405005                128    14.344487            poor
14    12.272389                179    35.679739            poor
15     9.511441                113    99.838416            good
16     9.421611                114    25.300848         average
17     6.501648                 15    96.949998            poor
18     8.777234                122    53.275589            good
19     4.956058                161    15.157823         average
20    10.317180                 35   100.727498            good
21    11.351271                 70    41.150216            good
22     7.311039                144    23.493537            good
23     4.827394                133    78.496591            good
24     8.068979                 27    84.453594            poor
25     8.076181                126    48.292317            good
26     3.844007                129    50.089190         average
27    12.282979                136    87.048586            good
28    11.245362                137    66.396757            good
29     3.336729                 61    15.632624            good
30     8.602354                 88    88.725557            good
31     7.926709                 39    21.490849            poor
32     1.335681                108    34.134087            good

In [30]:
df1.to_csv('health data.csv')

In [31]:
y= np.random.uniform(low=0,high=101,size=33).astype(int)
y  #health rating

array([ 38,  36,  94,  68,  11,  74,  56,  17,  14,  93,  50,  16,  91,
        77,  20,  93,  86,  53, 100,  36,  97,  21,  67,  62,  39,   9,
        19,  27,  85,  20,  39,  38,  14])

In [33]:
y.shape

(33,)

In [34]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')

X = np.array(ct.fit_transform(list1))

In [35]:
X

array([[0.0, 0.0, 1.0, 9.017514446686404, 72, 61.424020046481466],
       [0.0, 1.0, 0.0, 8.241171789738818, 114, 85.12581225307461],
       [0.0, 0.0, 1.0, 8.898744366814949, 78, 73.04413967158837],
       [1.0, 0.0, 0.0, 7.039450841845602, 90, 39.10886974518282],
       [0.0, 1.0, 0.0, 2.709238494933037, 76, 72.65817601850354],
       [0.0, 0.0, 1.0, 10.646695022583927, 66, 65.96698862454234],
       [0.0, 0.0, 1.0, 6.594812803950399, 95, 55.19030740308224],
       [0.0, 1.0, 0.0, 9.050327275174146, 83, 68.76417963034481],
       [0.0, 0.0, 1.0, 6.978364658693472, 156, 83.48024228929242],
       [0.0, 0.0, 1.0, 3.135331258365633, 133, 98.79451757919034],
       [0.0, 0.0, 1.0, 8.8938047787449, 78, 68.43089378748391],
       [1.0, 0.0, 0.0, 8.947787177821851, 176, 14.367127196131682],
       [0.0, 1.0, 0.0, 11.49557030809757, 87, 100.42762265260484],
       [0.0, 0.0, 1.0, 4.40500469185009, 128, 14.344487305738099],
       [0.0, 0.0, 1.0, 12.272388839254457, 179, 35.67973869105069],
 

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

We have now split the dataset.

In [37]:
X_train.shape

(22, 6)

In [38]:
y_test.shape

(11,)

In [39]:
from sklearn.linear_model import LinearRegression
obj1= LinearRegression()
obj1.fit(X_train,y_train)

LinearRegression()

Now the model has been trained.

In [41]:
y_pred= obj1.predict(X_test)
y_pred  #predicted rating of health.

array([64.08875494, 52.11259511, 49.32459378, 69.74907538, 47.18982234,
       44.83361582, 44.16701814, 58.93154342, 59.90311734, 63.07743941,
       44.19558363])

In [43]:
y_test #actual rating of health.

array([38, 93, 19, 53, 14, 93, 36, 21, 91, 38, 11])